apiVersion: apps/v1
kind: Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacheck-web
  template:
    metadata:
      labels:
        app: datacheck-web
    spec:
      containers:
        - name: datacheck-web
          image: datacheck-web:v2
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: FLASK_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: datacheck-config
                  key: FLASK_SECRET_KEY
            - name: FERNET_KEY
              valueFrom:
                secretKeyRef:
                  name: datacheck-secrets
                  key: FERNET_KEY
            - name: ENCRYPTED_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: datacheck-secrets
                  key: ENCRYPTED_CONN_STR
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: datacheck-secrets
                  key: GEMINI_API_KEY
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          imagePullPolicy: IfNotPresent
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600