apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: datacheck-secrets
  namespace: datacheck-web
data:
  FERNET_KEY: S200RVNXU2dqT2pRaFlERG15UHVJSWZ4WEU2MkU5WFd1NmNPSDB0eVA3MD0=
  GEMINI_API_KEY: QUl6YVN5RHVwdjZPeDVabmpQU2R0UFJrV2oyRmJzck9DRklGNHdR
  ENCRYPTED_CONN_STR: Z0FBQUFBQnBxZTJoYlNabjFtQlRrSUZuYktYdktWR0wyVXhTa2lrMS1Bd0tEVndHYVliRmY1SW45NFdldXVqVUw1TEgwUEpTeGZlZGhiSTJOWlJoWjFtTjU2LWxVUG1udTZQbUlwZ1NwaWlNRFFXWGNCeW1CdWlubTZsVWt4Y1lLZzZvdFlwQmV5ZkNVZTEtTzYweDhTU29UTHNVWEdQdy12U0dYN2FLSURuQThTQU9oSktWdnFjSmh2Qk4tZVNaTFZmcHBKeXhzZ1NZalNwamNSYlBCbnlpQWhKa0tNYy1xWU5WcWFueG9vbkl1RVpkb0VwZ3M5ST0=
