apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: datacheck-secrets
  namespace: datacheck-web
data:
<<<<<<< HEAD
  ENCRYPTED_CONN_STR: Z0FBQUFBQnBxYTR3a1hPVE9RVEpoNnlaY3ZOMGFsblphR1htZGRYdTZnbzNYNkVQTXZiT3lMQjhFVU00anB0TkhJTTA2YUxSVUYzNVFOMF8zQ2JrS05DdzBhQ3NzVHBCNTRIYUVkT2xQeXEwNmhmY0FadG15LTZsaFNDMTVzcTFHTGdmd3hkZVpoeklZVDl6eFU5MEhQS2paSl9PdGUwRGFuRXJJRklXbE9HVDFOX05YaVFoNU9laXRZZFZVUk84RF81MHpxMTBENlJDTjN1dGtrNkQ1SkpRTWY0YmdBUjZxTzFycTl6MTBjZHQ5ODF0Q1A0c3ZKcTgtLU1Rd2hVS2JZZ0JnU3VudU9ycw==
  FERNET_KEY: MEpJcGpkY0tHQUVKRGU2eUhVNTF3SUJpb3hObDBjenBFNlpPaUJfeFYwaz0=
  GEMINI_API_KEY: QUl6YVN5RHVwdjZPeDVabmpQU2R0MFBSa1dqMkZic3JPQ0ZJRzR3
=======
  FERNET_KEY: UkVQTEFDRV9NRV9CQVNFNjQ=
  ENCRYPTED_CONN_STR: UkVQTEFDRV9NRV9CQVNFNjQ=
  GEMINI_API_KEY: UkVQTEFDRV9NRV9CQVNFNjQ=
>>>>>>> ad5aa99 (Cambios en Dockerfile, secrets y requirements)
