apiVersion: v1
kind: Service
metadata:
  name: datacheck-service
  namespace: datacheck-web
spec:
  selector:
    app: datacheck-web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
